config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  root 'static_pages#index'
  get 'admin', to: 'static_pages#admin'
  resources :contactmessages, only: [:create, :new]
  resources :blogposts, only: [:show, :index] do 
    resources :comments, only: [:create]
  end
  namespace :admin do
    resources :blogposts, only: [:new, :create, :update, :edit, :destroy] do
      get :publish
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  validates :category, presence: true
  validates :content, presence: true
  validates :image, presence: true
  CATEGORIES = ['Technical', 'Others']

  has_many :comments, foreign_key: 'blog_id', dependent: :destroy
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 3}
  validates :message, presence: true, length: {minimum: 3}
  belongs_to :blogpost
end

app/models/contactmessage.rb
class Contactmessage < ActiveRecord::Base
  after_create :send_email_message

  validates :name, presence: true, length: {minimum: 3}
  validates :message, presence: true, length: {minimum: 3}
  validates :email, presence: true, length: {minimum: 3}
  
  def send_email_message 
    NotificationMailer.contact_message_email(self).deliver_now
  end
end

app/controllers/admin/blogposts_controller.rb
class Admin::BlogpostsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @blogpost = Blogpost.new
  end

  def create
    @blogpost = Blogpost.create(blogpost_params)
    if @blogpost.valid?
      redirect_to admin_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @blogpost = Blogpost.find_by_id(params[:id])
    render_not_found unless @blogpost.present?
  end

  def update
    @blogpost = Blogpost.find_by_id(params[:id])
    return render_not_found unless @blogpost.present?
    @blogpost.update_attributes(blogpost_params)      
    if @blogpost.valid?
      redirect_to admin_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blogpost = Blogpost.find_by_id(params[:id])
    return render_not_found unless @blogpost.present?
    @blogpost.destroy
    redirect_to admin_path
  end

  def publish
    @blogpost = Blogpost.find_by_id(params[:blogpost_id])
    return render_not_found unless @blogpost.present?
    publish = !@blogpost.published
    publish_date = publish == true ? Date.current() : nil
    @blogpost.update_attributes({:published => publish, :publish_date => publish_date})
    redirect_to admin_path
  end

  private

  def blogpost_params
    params.require(:blogpost).permit(:title, :content, :category, :image, :published, :publish_date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    admin_path
  end

  def render_not_found(status=:not_found)
    render text: '#{status.to_s.titleize}', status: status
  end

end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController  
  layout "blogposts"
  #use this layout for all
  def index
    @blogposts = Blogpost.all.select(&:publish_date).sort_by(&:publish_date).reverse!
    @sidebar = 'sidebar-blog-background'
    render(:layout => "layouts/application")
    #Action specific layout
  end

  def show 
    @comments = Comment.all
    @sidebar = 'sidebar-blog-background'
    @blogpost = Blogpost.find_by_id(params[:id])
    return render_not_found unless @blogpost.present?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blogpost = Blogpost.find_by_id(params[:blogpost_id])
    if @blogpost.blank?
      return render_not_found
    end
    @blogpost.comments.create(comment_params)
    redirect_to blogpost_path(@blogpost)
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :message)
  end
end

app/controllers/contactmessages_controller.rb
class ContactmessagesController < ApplicationController
  def create
    @sidebar = 'sidebar-contact-background'
    @contactmessage = Contactmessage.create(contactmessage_params)
    if @contactmessage.valid?
      @contactmessage = Contactmessage.new
      @displayform = 'hide-form'
      @displaysubmission = 'submission-thanks'
      render :new
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @sidebar = 'sidebar-contact-background'
    @displayform = 'contact-form'
    @displaysubmission = 'hide-submission'
    @contactmessage = Contactmessage.new
  end

  private

  def contactmessage_params
    params.require(:contactmessage).permit(:name, :email, :message);
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_admin!, only: [:admin]
  def index
    @sidebar = 'sidebar-index-background'
  end

  def admin
    @messages = Contactmessage.all
    @blogposts = Blogpost.all
    render(:layout => "layouts/blogposts")
  end
end

app/helpers/admin/blogposts_helper.rb
module Admin::BlogpostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contactmessages_helper.rb
module ContactmessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/blogposts/edit.html.erb
<div class='admin-box'>
  <h1>Edit Post</h1>
  <%= simple_form_for @blogpost, url: admin_blogpost_path(@blogpost), method: :patch do |f| %>
    <%= f.input :title %>
    <%= f.input :image %>
    <%= f.input :category, as: :select, collection: Blogpost::CATEGORIES %>
    <%= f.input :content, :as => :ckeditor, :input_html => {:ckeditor => {:toolbar => 'FULL'}} %>
    </br>
     <%= f.submit 'Update', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/admin/blogposts/new.html.erb
<div class='admin-box'>
  <h1>Create Post</h1>
  <%= simple_form_for @blogpost, url: admin_blogposts_path, method: :post do |f| %>
    <%= f.input :title %>
    <%= f.input :image %>
    <%= f.input :category, as: :select, collection: Blogpost::CATEGORIES %>
    <%= f.input :content, :as => :ckeditor, :input_html => {:ckeditor => {:toolbar => 'FULL'}} %>
    </br>
     <%= f.submit 'Create', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/blogposts/index.html.erb
<div class="blog-index-box">
  <h1>Blog Archive</h1>
  <div class='post-index-container'>
    <% @blogposts.each do |post| %>
      <% if post.published? %>
        <br/> 
      <div class='post-index-box'>
          <div class='post-index-title'>
            <h2><%= link_to post.title, blogpost_path(post) %></h2>
            <p><%= post.publish_date.strftime('%B %e %Y') %></p>
            <p>BY <%= link_to 'JOSHUA TAN', root_path, class: 'post-author' %></p>              
          </div>      
          <div class='post-index-text'>
            <%= truncate(strip_tags(post.content), length: 250, separator: ' ') %>
          </div>

          <p><%= link_to 'Read More', blogpost_path(post) %></p>
      </div>   
      <br/>
    <% end %>
  <% end %>
  </div>
</div>

app/views/blogposts/show.html.erb
  <div class='blog-header' style="background-image: url(<%= image_path(@blogpost.image)%>)">
    <div class='blog-header-content' >
      <div class="blog-site-navigation">
        <nav class="blog-primary-navigation">
          <ul class="blog-nav-menu">
            <li><%= link_to 'Blog Index', blogposts_path %></li>
            <li><%= link_to 'About Me', root_path %></li>          
            <li><%= link_to 'Contact', new_contactmessage_path %>
            </li>
            <% if admin_signed_in? %>
              <li><%= link_to 'Admin Page', admin_path %></li>
              <li><%= link_to 'Admin Sign Out', destroy_admin_session_path, method: :delete %></li>
            <% end %>          
          </ul>
        </nav>                               
      </div><!-- .site-navigation -->
      <div class='blog-title-content'>
        <h1><%= @blogpost.title %></h1>
        <ul>
          <li><%= @blogpost.created_at.to_time.strftime('%B %e %Y') %></li>
          <li>By Joshua Tan</li>
        </ul>
      </div>               
    </div>
  </div>

<div class='blog-box'>
  <div class='blog-content'>
    <%= @blogpost.content.html_safe %>
  </div>
</div>

<div class='comment-box'>
  <div class='comments'>
    <h2>Comments</h2>
    <br/>
    <% @comments.each do |comment| %>      
    <div class='comment'>
      <p><span><%= comment.name %></span> commented on <span><%=comment.created_at.strftime('%B %e %Y')%></span></p>
      <p><%= comment.message %></p>      
    </div>
    <% end %>
  </div>
  <br/><br/>
  <div class='comment-input'>
    <%= simple_form_for Comment.new, url: blogpost_comments_path(@blogpost) do |f| %>
      <%= f.input :name %>
      <%= f.input :message %>
      <br/>
      <%= f.submit 'Comment', class: 'btn btn-default', id: 'submit-button' %>
    <% end %>
  </div>


</div>

app/views/contactmessages/new.html.erb
<%= javascript_include_tag 'contactpage' %>
<div class="contact-container">
  <div class="contact-inner">
    <h1>Get in Touch!</h1>
    <br/><br/>
    <p class= "contact-text">Drop me a message...</p>
    <%= simple_form_for @contactmessage, html: {class: @displayform} do |f| %>
      <%= f.input :name %>    
      <br/>
      <%= f.input :email %>
      <br/>
      <%= f.input :message %>
      <br/>
      <%= f.submit 'Send', class: 'btn btn-default btn-lg', id: 'contact-submit' %>
    <% end %>
    <div class=<%= @displaysubmission %>>
      <h1>Thanks for the message!</h1>
      <br/>
      <%= link_to 'Click here to send another message', new_contactmessage_path %>
    </div>
    <br/><br/>
    <p class= "contact-text">Or let's get in touch using...</p>
    <div class="contact-social">
      <div class="contact-icons">
        <%= mail_to 'tantohyung@gmail.com' do %>
          <span class="contact-icons icon-envelope"></span>
          <p class="contact-icons-text">EMAIL</p>
        <% end %>
      </div>
      <div class="contact-icons">
        <a href="https://mobile.twitter.com/tantohyung">
          <span class="contact-icons icon-twitter"></span>
          <p class="contact-icons-text">TWITTER</p>
        </a>
      </div>
      <div class="contact-icons">
        <a href="https://www.facebook.com/profile.php?id=100012764088443">
          <span class="contact-icons icon-facebook"></span>
          <p class="contact-icons-text">FACEBOOK</p>
        </a>
      </div>      
      <div class="contact-icons">
        <a href="https://plus.google.com/103690899611882314643/posts">      
          <span class="contact-icons icon-googleplus"></span>
          <p class="contact-icons-text">GOOGLE PLUS</p>
        </a>
      </div>            
      <div class="contact-icons">
        <a href="https://github.com/tohyung85">            
          <span class="contact-icons fontello-github-circled contact-github"></span>   
          <p class="contact-icons-text">GITHUB</p>
        </a>
      </div>                     
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joshua Tan</title>
  <meta name="viewport" content="initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,700italic,400italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,400italic,600italic,600' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Archivo+Narrow:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.viewportchecker.min' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="sidebar <%= @sidebar %>">
  <div class="sidebar-inner">           
    <header id="masthead" class="site-header">
      <div class="site-branding">
        <div class="site-title"><%= link_to 'Joshua Tan', root_path %></div>                                                              
        <div class="site-description">
          <h2>Rails Web Developer</h2> 
          <p>Turning your ideas into reality</p>
        </div>

        <nav class="social-menu" role="navigation">
          <ul class="social">
            <li><a href="https://mobile.twitter.com/tantohyung"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            <li><a href="https://www.facebook.com/profile.php?id=100012764088443"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
            <li><a href="https://plus.google.com/103690899611882314643/posts"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
            <li><a href="https://github.com/tohyung85"><i class="fa fa-github" aria-hidden="true"></i></a></li>
          </ul>
        </nav>
                            
        <div class="site-navigation">
          <nav class="primary-navigation">
            <ul class="nav-menu">
              <li><%= link_to 'Blog', blogposts_path %></li>
              <li><%= link_to 'About Me', root_path %></li>          
              <li><%= link_to 'Contact', new_contactmessage_path %>
              </li>
              <% if admin_signed_in? %>
                <li><%= link_to 'Admin Page', admin_path %></li>
                <li><%= link_to 'Admin Sign Out', destroy_admin_session_path, method: :delete %></li>
              <% end %>          
            </ul>
          </nav>                               
        </div><!-- .site-navigation -->        
      </div><!-- .site-branding -->
    </header><!-- .site-header -->            
  </div><!-- .sidebar-inner -->
</div>


<div class="site-content">
  <div class="page-content">
    <% if notice.present? %>
      <p class="notice alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>    
    <%= yield %>
  </div>

  <div id="footer">

      <p class="footer-comments">Brought to you by Joshua</p>
      
      <div class= "footer-links">
        <%= link_to 'Contact Me', new_contactmessage_path %>
      </div>
      

      <ul class="footer-social">
        <li><a href="https://mobile.twitter.com/tantohyung"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
        <li><a href="https://www.facebook.com/profile.php?id=100012764088443"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
        <li><a href="https://plus.google.com/103690899611882314643/posts"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
        <li><a href="https://github.com/tohyung85"><i class="fa fa-github" aria-hidden="true"></i></a></li>
      </ul>
  </div>
</div>



</body>
</html>

app/views/layouts/blogposts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joshua Tan</title>
  <meta name="viewport" content="initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,700italic,400italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,400italic,600italic,600' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Archivo+Narrow:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'highlight.pack' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="sidebar <%= @sidebar %> mobile-hide">
  <div class="sidebar-inner">            
    <header id="masthead" class="site-header">
      <div class="site-branding">
        <div class="site-title"><%= link_to 'Joshua Tan', root_path %></div>                                                              
        <div class="site-description">
          <h2>Rails Web Developer</h2> 
          <p>Turning your ideas into reality</p>
        </div>

        <nav class="social-menu" role="navigation">
          <ul class="social">
            <li><a href="https://mobile.twitter.com/tantohyung"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            <li><a href="https://www.facebook.com/profile.php?id=100012764088443"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
            <li><a href="https://plus.google.com/103690899611882314643/posts"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
            <li><a href="https://github.com/tohyung85"><i class="fa fa-github" aria-hidden="true"></i></a></li>
          </ul>
          </ul>
        </nav>
                            
        <div class="site-navigation">
          <nav class="primary-navigation">
            <ul class="nav-menu">
              <li><%= link_to 'Blog', blogposts_path %></li>
              <li><%= link_to 'About Me', root_path %></li>          
              <li><%= link_to 'Contact', new_contactmessage_path %>
              </li>
              <% if admin_signed_in? %>
              <li><%= link_to 'Admin Page', admin_path %></li>
              <li><%= link_to 'Admin Sign Out', destroy_admin_session_path, method: :delete %></li>
              <% end %>          
            </ul>
          </nav>                               
        </div><!-- .site-navigation -->        
      </div><!-- .site-branding -->
    </header><!-- .site-header -->            
  </div><!-- .sidebar-inner -->
</div>


<div class="site-content">
  <div class="page-content">
    <% if notice.present? %>
      <p class="notice alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>        
    <%= yield %>
  </div>

  <div id="footer">

      <p class="footer-comments">Brought to you by Joshua</p>
      
      <div class= "footer-links">
        <%= link_to 'Contact Me', new_contactmessage_path %>
      </div>
      

      <ul class="footer-social">
        <li><a href="https://mobile.twitter.com/tantohyung"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
        <li><a href="https://www.facebook.com/profile.php?id=100012764088443"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
        <li><a href="https://plus.google.com/103690899611882314643/posts"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
        <li><a href="https://github.com/tohyung85"><i class="fa fa-github" aria-hidden="true"></i></a></li>
      </ul>
  </div>
</div>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Joshua Tan</title>
  <meta name="viewport" content="initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,700italic,400italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,400italic,600italic,600' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Julius+Sans+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Archivo+Narrow:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.viewportchecker.min' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="sidebar <%= @sidebar %>">
  <div class="sidebar-inner">           
    <header id="masthead" class="site-header">
      <div class="site-branding">
        <div class="site-title"><%= link_to 'Joshua Tan', root_path %></div>                                                              
        <div class="site-description">
          <h2>My Private Workspace!</h2> 
          <p>Let's do this!</p>
        </div>
                            
        <div class="site-navigation">
          <nav class="primary-navigation">
            <ul class="nav-menu">
              <li><a href="#">Blog</a></li>
              <li><%= link_to 'My Messages', root_path %></li>
              <li><%= link_to 'Contact', new_contactmessage_path %>
              </li>
              <% if admin_signed_in? %>
              <li><%= link_to 'Admin Sign Out', destroy_admin_session_path, method: :delete %></li>
              <% end %>          
            </ul>
          </nav>                               
        </div><!-- .site-navigation -->        
      </div><!-- .site-branding -->
    </header><!-- .site-header -->            
  </div><!-- .sidebar-inner -->
</div>


<div class="site-content">
  <div class="page-content">
    <% if notice.present? %>
      <p class="notice alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>    
    <%= yield %>
  </div>

  <div id="footer">

      <p class="footer-comments">Brought to you by Joshua</p>
      
      <div class= "footer-links">
        <%= link_to 'Contact Me', new_contactmessage_path %>
      </div>
      

      <ul class="footer-social">
        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
        <li><a href="#"><i class="fa fa-github" aria-hidden="true"></i></a></li>
      </ul>
  </div>
</div>



</body>
</html>

app/views/static_pages/admin.html.erb
<div class='admin-box'>
  <h1>Admin Page</h1>

  <section class="messages-section">
    <h2>Messages</h2>
    <% @messages.each do |message|  %>
      <div class='message-box'>
        <p><%= message.name %></p>
        <p><%= message.email %></p>
        <p><%= message.message %></p>
      </div>
    <% end %>
  </section>
  <br/><br/>
  <section class='blog-section'>
    <h2>Blogs</h2>
    <% @blogposts.each do |blogpost| %>
      <div class='blogpost-box'>
        <div class='blog-text'>
          <p><%= blogpost.title %></p>
          <%= link_to 'View Post', blogpost_path(blogpost) %>
        </div>
        <div class='blog-buttons'>
          <% if blogpost.published == false %>
            <%= link_to 'Publish', admin_blogpost_publish_path(blogpost), class: 'btn btn-primary'%>
          <% else %>
            <%= link_to 'Unpublish', admin_blogpost_publish_path(blogpost), class: 'btn btn-warning'%>
          <% end %>
          <%= link_to 'Edit Post', edit_admin_blogpost_path(blogpost), class: 'btn btn-warning'%>
          <%= link_to 'Delete Post', admin_blogpost_path(blogpost), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-warning'%>
        </div>
      </div>
      <br/>
    <% end %>
    <%= link_to 'New Post', new_admin_blogpost_path, class: 'btn btn-success' %>
  </section>
</div>

app/views/static_pages/index.html.erb
<%= javascript_include_tag 'about'%>
<div class="about-container">
  <div class="about-box about-me-box">
    <h1>About Me</h1>
    <br/>
    <div class="col-xs-2 about-image-div">
      <%= image_tag("joshua.jpg", class: "about-image img-responsive")%>
      <div class="loading-circle">
        <div class="circularGcircle">
          <div id="circularG_1" class="circularG"></div>
          <div id="circularG_2" class="circularG"></div>
          <div id="circularG_3" class="circularG"></div>
          <div id="circularG_4" class="circularG"></div>
          <div id="circularG_5" class="circularG"></div>
          <div id="circularG_6" class="circularG"></div>
          <div id="circularG_7" class="circularG"></div>
          <div id="circularG_8" class="circularG"></div>
        </div>      
      </div>
    </div>
    <div class="about-me-text col-xs-10">
      <p>I am a full stack web developer from Singapore. I am passionate about coding which led me to pick up and learn the details of web development using rails and javascript.</p>
      <p>I am comfortable with frontend and backend techniques, take pride in what i do and believe in delivering quality code to the best of my ability. </p>
      <p>I enjoy working on minor details whether it is to improve the design or performance of my web apps. I also love working as a team and believe that we can achieve more by working together.</p>
    </div>
    <br class="clr"/>
  </div>

  <div class="about-box">
    <div class="skill-box">
      <h1>Skills</h1>
      <div class="skill col-xs-12 col-sm-6">
        <p>Ruby on Rails</p>
        <div class="skill-meter"><div class="competence rails-competence"></div></div>
      </div>

      <div class="skill col-xs-12 col-sm-6">
        <p>Javascript</p>
        <div class="skill-meter"><div class="competence javascript-competence"></div></div>
      </div>

      <div class="skill col-xs-12 col-sm-6">
        <p>HTML</p>
        <div class="skill-meter"><div class="competence html-competence"></div></div>
      </div>

      <div class="skill col-xs-12 col-sm-6">
        <p>CSS</p>
        <div class="skill-meter"><div class="competence css-competence"></div></div>
      </div>
    </div>
  </div>

  <div class="about-box">
    <h1>Projects</h1>
    <div class="projects-box">
      <div class="project-image">
        <a href="https://coding-pals.herokuapp.com/">
          <%= image_tag("codingpals.png") %>
          <div class="loading-circle">
            <div class="circularGcircle">
              <div id="circularG_1" class="circularG"></div>
              <div id="circularG_2" class="circularG"></div>
              <div id="circularG_3" class="circularG"></div>
              <div id="circularG_4" class="circularG"></div>
              <div id="circularG_5" class="circularG"></div>
              <div id="circularG_6" class="circularG"></div>
              <div id="circularG_7" class="circularG"></div>
              <div id="circularG_8" class="circularG"></div>
            </div>      
          </div>          
        </a>
      </div>
      <div class="projects-list" >
        <%= link_to("https://coding-pals.herokuapp.com/") do %>
          <div class="project" data-id="1">
            <h2>Coding Pals</h2>
            <p>Languages and Frameworks: Ruby, Rails, Javascript</p>
            <p>Find coders who wish to learn stuff together</p>
          </div>
        <% end %>

        <%= link_to("http://chess-fusion.herokuapp.com/") do %>
          <div class="project" data-id="2">
            <h2>Chess Fusion</h2>
            <p>Languages and Frameworks: Ruby, Rails, Javascript</p>
            <p>Rails based web application for playing games of chess</p>
          </div>            
        <% end %>

        <%= link_to("https://jt-news-stop.herokuapp.com/") do %>
          <div class="project" data-id="3">
            <h2>News Stop</h2>
            <p>Languages and Frameworks: Ruby, Rails</p>
            <p>App that compiles breaking news from major news sites</p>
          </div>
        <% end %>

        <%= link_to("http://codepen.io/tohyung85/full/rxEZKy/") do %>
          <div class="project" data-id="4">
            <h2>Game of Life</h2>
            <p>Languages and Frameworks: Javascript, ReactJS</p>
            <p>Conway's Game of Life App</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>